spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_picture?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  session:
    redis:
      namespace: "coderjia:session"   # 定义存储在 Redis 中的 session 数据的命名空间
      flush-mode: on_save             # 每次保存或更新 session 时立即将数据同步到 Redis
      save-mode: always               # 每次请求结束时都保存 session